spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=${PORT:8082}
spring.security.user.name=Adi
spring.security.user.password=404
jwt.secretKey=${JWT_SECRETKEY}
jwt.expirationMs=86400000
