spring.datasource.url=jdbc:postgresql://localhost:5432/SpringStore_DB
spring.datasource.username=postgres
spring.datasource.password=error404
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=false
#server.servlet.context-path=/api/v1
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8082
spring.security.user.name=Adi
spring.security.user.password=404
jwt.secretKey=asdfhads9f67as98dfyaisudhfa98s67dfy89aishudfuays89dfyasi8df7asdf87987g98a7sg986a89sdf7y
jwt.expirationMs=86400000